language: R
cache: packages

sudo: required
dist: xenial
latex: false

r_github_packages:
  - r-spatial/sf
  - r-spatial/lwgeom
r: 
  - release
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

warnings_are_errors: false

env:
  global:
    -_R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - sudo apt-get update