language: R
cache: packages

sudo: required
dist: trusty
cache: false
latex: false

r: 
  - release

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

warnings_are_errors: false

before_install:
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
  
env:
  global:
    -_R_CHECK_FORCE_SUGGESTS_=false

