---
title: "Testing Simple Features"
author: "Marc Weber"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: yeti
    highlighted: default 
    toc: yes
---

## Purpose
From Tony's email on 2/15/2017:

"Some example files are in L:\Priv\ARM Data\NARS Statistics Research\spsurvey2\Test_Data

SFS….  Is a stream network.
Grid….  Is a 4 by 4 grid that covers the bbox of SFS….
Red….  Is a polygon file of Delaware wetlands.
Nc….  Is polygons of counties of North Carolina (used in sf examples)

I can use st_read read these files and st_write was used to create nc….   I created the grid using st_makegrid function.

Questions:
•	How do I find the midpoint (or “centroid”) of a stream feature.  Allows me to treat the stream features as points for some operations.
•	How do I split stream features into two features.  I can use st_segmentize to make any segment < specified length but it does not split feature into two features.
•	How do I intersect the polygons in a file with a grid and split the polygons into parts of the polygons within each grid cell.  Need to be able to select cell size of the grid (raster?)
•	I do not understand the function st_intersect.  I used the Grid and SFS sf objects expecting that it would tell me which grid cell each stream feature belonged to.  Results seemed to put a segment that was clearly only in one grid cell into several grid cells.  At least that is how I interpreted the T/F output table.  Worked when I did it using Red… polygons.
"


### Read in stream network and demonstrate generating midpoint / centroid
```{r, eval=F}
library(sf)
streams <- st_read('L:/Priv/ARM Data/NARS Statistics Research/spsurvey2/Test_Data/SFS_FinalFrame_HUC5_20120705.shp')
attr(streams, "sf_column")
print(streams[27], n = 3) # just geometry column
methods(class='sf')
stream.geom <- st_geometry(streams)
# or
stream.geom <- streams$geom
# or 
stream.geom <- streams[[27]]
# look at first geometry / first feature
stream.geom[[1]]
stream.geom[[1]][1]
methods(class = 'sfc')
test <- st_point(stream.geom)
```