---
title: "Debug New GRTS"
author: "Tony Olsen"
date: "`r format(Sys.time(),  '%B %d, %Y')`"
output: 
  html_document:
    highlighted: default
    number_sections: true
    theme: cosmo
    toc: yes
    code_folding: show
    toc_float:
      collapsed: no
      smooth_scroll: yes
    df_print: paged
    fig_caption: yes
    depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library paths}
library(sf)
library(dplyr)

```

Source grtspts files
```{r}
pathgrts <- "C:/Users/tolsen/Documents/spsurvey/R/"
source(paste0(pathgrts, "dsgn_check.R"))
source(paste0(pathgrts, "grts.R"))
source(paste0(pathgrts, "grtspts_ip.R"))
source(paste0(pathgrts, "grts_stratum.R"))
source(paste0(pathgrts, "grtspts_mindis.R"))
source(paste0(pathgrts, "grtspts_ipleg.R"))
source(paste0(pathgrts, "get_address.R"))
source(paste0(pathgrts, "UPpivotal.R"))
source(paste0(pathgrts, "replace_near.R"))
source(paste0(pathgrts, "rho.R"))
source(paste0(pathgrts, "stopprnt.R"))
source(paste0(pathgrts, "warndsgn.R"))

source(paste0(pathgrts, "irs.R"))
source(paste0(pathgrts, "irs_stratum.R"))
source(paste0(pathgrts, "irspts_mindis.R"))

```

# grts test for points
```{r}
path <- "C:/Users/tolsen/Documents/spsurvey/notes/"

sframe <- read_sf(paste0(path, "Lakes.shp"))
st_crs(sframe) <- 5069

glimpse(sframe)
sframe

Equalsites <- grts(sframe = sframe, n.samp = 100)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# stratified; unequal prob
Equalsites <- grts(sframe = sframe, n.samp = c(16, 16, 16), stratum = c("CT", "RI", "MA"),
                  stratum_var = "ST", caty_var = "AREA_CAT",
                  caty.n = c("(0,1]" = 0, "(1,5]" = 4, "(10,50]" = 4, "(5,10]" = 4, ">50" = 4))
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# mindis
Equalsites <- grts(sframe = sframe, n.samp = 100, mindis = 7000)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# with n.over
Equalsites <- grts(sframe = sframe, n.samp = 100, n.over = 10)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)
plot(st_geometry(Equalsites$sites.over), pch = 16, col = 'blue', add = TRUE)

# with n.near
Equalsites <- grts(sframe = sframe, n.samp = 100, n.near = 5)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = "+", col = 'red', add = TRUE)
plot(st_geometry(Equalsites$sites.near), pch = 16, col = 'blue', add = TRUE)

# with legacy sites
Equalsites <- grts(sframe = sframe, n.samp = 100, legacy_option = TRUE, legacy_var = "HIST_LAKE")
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = "+", col = 'red', add = TRUE)
plot(st_geometry(subset(Equalsites$sites.base, !is.na(Equalsites$sites.base$legacy))), 
                 pch = 16, col = 'red', add = TRUE)

# with legacy sites and mindis
Equalsites <- grts(sframe = sframe, n.samp = 100, legacy_option = TRUE, legacy_var = "HIST_LAKE",
                   mindis = 5000)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = "+", col = 'red', add = TRUE)
plot(st_geometry(subset(Equalsites$sites.base, !is.na(Equalsites$sites.base$legacy))), 
                 pch = 16, col = 'red', add = TRUE)

```

# irs test for points
```{r}
path <- "C:/Users/tolsen/Documents/spsurvey/notes/"

sframe <- read_sf(paste0(path, "Lakes.shp"))
st_crs(sframe) <- 5069

glimpse(sframe)
sframe

# basic
Equalsites <- irs(sframe = sframe, n.samp = 100)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# stratified; unequal prob
Equalsites <- irs(sframe = sframe, n.samp = c(16, 16, 16), stratum = c("CT", "RI", "MA"),
                  stratum_var = "ST", caty_var = "AREA_CAT",
                  caty.n = c("(0,1]" = 0, "(1,5]" = 4, "(10,50]" = 4, "(5,10]" = 4, ">50" = 4))

plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# mindis
Equalsites <- grts(sframe = sframe, n.samp = 100, mindis = 7000)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# with n.near
Equalsites <- grts(sframe = sframe, n.samp = 100, n.near = 5)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = "+", col = 'red', add = TRUE)
plot(st_geometry(Equalsites$sites.near), pch = 16, col = 'blue', add = TRUE)
```




# test for areas

```{r}
path <- "C:/Users/tolsen/Documents/spsurvey/notes/"

sframe <- read_sf(paste0(path, "SCECAP_2010_Estuary.shp"))

sum(st_area(sframe))

# basic design
Equalsites <- grts(sframe = sframe, pt_density = 1/1000000,  n.samp = 100)
plot(st_geometry(sframe), pch = "+")
plot(st_geometry(Equalsites$sites.base), pch = "+", col = 'red', add = TRUE)

# mindis option
Equalsites <- grts(sframe = sframe, pt_density = 1/1000000, mindis = 1000, n.samp = 100)
plot(st_geometry(sframe))
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# legacy site option
# first generate set of legacy sites
legacy_sites <- grts(sframe = sframe, pt_density = 1/1000000,  n.samp = 20)
legacy_sites <- legacy_sites$sites.base
legacy_sites$legacyID <- legacy_sites$siteID
plot(st_geometry(sframe))
plot(st_geometry(legacy_sites), pch = 16, col = 'red', add = TRUE)
# design with legacy sites
Equalsites <- grts(sframe = sframe, pt_density = 1/1000000, n.samp = 100, 
                      legacy_sites = legacy_sites, legacy_option = TRUE, legacy_var = "legacyID")
plot(st_geometry(sframe))
plot(st_geometry(Equalsites$sites.base), pch = "+", col = 'red', add = TRUE)
plot(st_geometry(Equalsites$sites.base[!is.na(Equalsites$sites.base$legacy),]), 
     pch = 16, col = 'red', add = TRUE)
# design with legacy and mindis
Equalsites <- grts(sframe = sframe, pt_density = 1/1000000, n.samp = 100, mindis = 1000,
                      legacy_sites = legacy_sites, legacy_option = TRUE, legacy_var = "legacyID")
plot(st_geometry(sframe))
plot(st_geometry(Equalsites$sites.base), pch = "+", col = 'red', add = TRUE)
plot(st_geometry(Equalsites$sites.base[!is.na(Equalsites$sites.base$legacy),]), 
     pch = 16, col = 'red', add = TRUE)
```


# test for linear

```{r}
path <- "C:/Users/tolsen/Documents/spsurvey/notes/"
# read sample frame
sframe <- read_sf(paste0(path, "Delaware_flowlines.shp"))

# basic design
Equalsites <- grts(sframe = sframe, pt_density = 1/10000, n.samp = 100)
plot(st_geometry(sframe))
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# mindis option
Equalsites <- grts(sframe = sframe, pt_density = 1/1000, mindis = 5000, n.samp = 100)
plot(st_geometry(sframe))
plot(st_geometry(Equalsites$sites.base), pch = 16, col = 'red', add = TRUE)

# legacy site option
# first generate set of legacy sites
legacy_sites <- grts(sframe = sframe, pt_density = 1/10000,  n.samp = 20)
legacy_sites <- legacy_sites$sites.base
legacy_sites$legacyID <- legacy_sites$siteID
plot(st_geometry(sframe))
plot(st_geometry(legacy_sites), pch = 16, col = 'red', add = TRUE)
# design with legacy sites
Equalsites <- grts(sframe = sframe, pt_density = 1/10000, n.samp = 100, 
                      legacy_sites = legacy_sites, legacy_option = TRUE, legacy_var = "legacyID")
plot(st_geometry(sframe))
plot(st_geometry(Equalsites$sites.base), pch = "+", col = 'red', add = TRUE)
plot(st_geometry(Equalsites$sites.base[!is.na(Equalsites$sites.base$legacy),]), 
     pch = 16, col = 'red', add = TRUE)
```






