library(spsurvey)
library(tools)
setwd("C:/Users/mweber/Downloads")
Sweave("C:/Users/mweber/Downloads/test2.Rnw")
texi2pdf("C:/Users/mweber/Downloads/test2.tex")
Stangle("Finite_Design.Rnw", annotate=FALSE)
