###############################################################################
# Function: cat_analysis (exported)
# Programmer: Tom Kincaid
# Date: July 23, 2020
# Revised: August 14, 2020 to allow use of an sf object as the input data
#          argument (dframe)
# Revised: December 15, 2020 to allow use of the Horvitz-Thompson and
#          Yates-Grundy variance estimators and to use a new function named
#          survey_design to create the survey design object
# Revised: March 2, 2021 to revise the process for creating unique site ID
#          values
# Revised: April 7, 2021 to ensure that the dframe argument does not contain
#          zero rows
#'
#' Categorical Data Analysis for Probability Survey Data
#'
#' This function organizes input and output for analysis of categorical data
#' generated by a probability survey.  The input data argument can be either a
#' data frame or a simple features (sf) object.  If an sf object is used,
#' coordinates are extracted from the geometry column in the object, arguments
#' \code{xcoord} and \code{ycoord} are assigned values \code{"xcoord"} and \code{"ycoord"},
#' respectively, and the geometry column is dropped from the object.
#'
#' @param dframe Data frame containing survey design variables, response
#'   variables, and subpopulation (domain) variables.
#'
#' @param vars Vector composed of character values that identify the
#'   names of response variables in the \code{dframe} data frame.
#'
#' @param subpops Vector composed of character values that identify the
#'   names of subpopulation (domain) variables in the \code{dframe} data frame.
#'   If a value is not provided, the value \code{"All_Sites"} is assigned to the
#'   subpops argument and a factor variable named \code{"All_Sites"} that takes the
#'   value \code{"All Sites"} is added to the \code{dframe} data frame.  The default
#'   value is \code{NULL}.
#'
#' @param siteID Character value providing name of the site ID variable in
#'   the \code{dframe} data frame.  For a two-stage sample, the site ID variable
#'   identifies stage two site IDs.  The default value is \code{"siteID"}.
#'
#' @param weight Character value providing name of the survey design weight
#'   variable in the \code{dframe} data frame.  For a two-stage sample, the weight
#'   variable identifies stage two weights.  The default value is \code{"weight"}.
#'
#' @param xcoord Character value providing name of the x-coordinate variable in
#'   the \code{dframe} data frame.  For a two-stage sample, the x-coordinate variable
#'   identifies stage two x-coordinates.  Note that x-coordinates are required
#'   for calculation of the local mean variance estimator.  The default value is
#'   \code{NULL}.
#'
#' @param ycoord Character value providing name of the y-coordinate variable in
#'   the \code{dframe} data frame.  For a two-stage sample, the y-coordinate variable
#'   identifies stage two y-coordinates.  Note that y-coordinates are required
#'   for calculation of the local mean variance estimator.  The default value is
#'   \code{NULL}.
#'
#' @param stratumID Character value providing name of the stratum ID variable in
#'   the \code{dframe} data frame.  The default value is \code{NULL}.
#'
#' @param clusterID Character value providing name of the cluster (stage one) ID
#'   variable in the \code{dframe} data frame.  Note that cluster IDs are required for
#'   a two-stage sample.  The default value is \code{NULL}.
#'
#' @param weight1 Character value providing name of the stage one weight
#'   variable in the \code{dframe} data frame.  The default value is \code{NULL}.
#'
#' @param xcoord1 Character value providing name of the stage one x-coordinate
#'   variable in the \code{dframe} data frame.  Note that x-coordinates are required
#'   for calculation of the local mean variance estimator.  The default value is
#'   \code{NULL}.
#'
#' @param ycoord1 Character value providing name of the stage one y-coordinate
#'   variable in the \code{dframe} data frame.  Note that y-coordinates are required
#'   for calculation of the local mean variance estimator.  The default value is
#'   \code{NULL}.
#'
#' @param sizeweight Logical value that indicates whether size weights should be
#'   used during estimation, where \code{TRUE} = use size weights and
#'   \code{FALSE} = do not use size weights. To employ size weights for a
#'   single-stage sample, a value must be supplied for argument weight.  To
#'   employ size weights for a two-stage sample, values must be supplied for
#'   arguments \code{weight} and \code{weight1}. The default value is \code{FALSE}.
#'
#' @param sweight Character value providing name of the size weight variable in
#'   the \code{dframe} data frame.  For a two-stage sample, the size weight variable
#'   identifies stage two size weights.  The default value is \code{NULL}.
#'
#' @param sweight1 Character value providing name of the stage one size weight
#'   variable in the \code{dframe} data frame.  The default value is \code{NULL}.
#'
#' @param popcorrect Logical value that indicates whether the finite population
#'   correction factor is used during variance estimation. To employ the
#'   correction factor for a single-stage sample, values must be supplied for
#'   argument \code{fpcsize}.  To employ the correction factor for a two-stage sample,
#'   values must be supplied for arguments \code{Ncluster} and \code{stage1size}.
#'   The default value is \code{FALSE}.
#'
#' @param fpcsize Character value providing name of the variable in the \code{dframe}
#'   data frame that identifies size of the resource, which is required for
#'   calculation of the finite population correction factor for a single-stage
#'   sample.  Defaults to the number of observations in \code{dframe} if
#'   \code{popcorrect = TRUE}.
#'
#' @param Ncluster Character value providing name of the variable in the \code{dframe}
#'   data frame that identifies the number of clusters (stage one sampling
#'   units) in the resource, which is required for calculation of the finite
#'   population correction factor for a two-stage sample.  This argument is also
#'   required for a two-stage sample when the popsize argument is not equal to
#'   \code{NULL} and the vartype argument equals \code{"Local"}.  The default value is \code{NULL}.
#'
#' @param stage1size Character value providing name of the variable in the
#'   \code{dframe} data frame that identifies cluster size, i.e. the number of the
#'   stage two sampling units in the resource for a cluster.  Note that cluster
#'   size is required for calculation of the finite population correction factor
#'   for a two-stage sample. The default value is \code{NULL}.
#'
#' @param popsize Object that provides values for the population argument of the
#'   \code{calibrate} or \code{postStratify} functions.  For the \code{calibrate}
#'   function, the object is a named list, where the names identify factor
#'   variables in the \code{dframe} data frame.  Each element of the list is a
#'   named vector containing the population total for each level of the associated
#'   factor variable.  For the \code{postStratify} function, the object is either
#'   a data frame, table, or xtabs object that provides the population total for all
#'   combinations of selected  factor varaibles in the \code{dframe} data frame.
#'   If a data frame is used for \code{popsize}, the variable containing population
#'   totals must be the last variable in the data frame.  If a table is used for
#'   \code{popsize}, the table must have named dimnames where the names identify
#'   factor variables in the \code{dframe} data frame.  If the \code{popsize}
#'   argument is equal to \code{NULL}, then neither calibration nor
#'   post-stratification is performed.  The default value is
#'   \code{NULL}.\cr\cr
#'   Example popsize for calibration:\cr
#'     popsize <- list(Ecoregion = c(East = 750,\cr
#'                                   Central = 500,\cr
#'                                   West = 250),\cr
#'                     Type = c(Streams = 1150,\cr
#'                              Rivers = 350))\cr
#'   Example popsize for post-stratification using a data frame:\cr
#'     popsize <- data.frame(
#'       Ecoregion = rep(c("East", "Central", "West"), rep(2, 3)),\cr
#'       Type = rep(c("Streams", "Rivers"), 3),\cr
#'       Total = c(575, 175, 400, 100, 175, 75))\cr
#'   Example popsize for post-stratification using a table:\cr575
#'     popsize <- with(MySurveyFrame, table(Ecoregion, Type))\cr
#'   Example popsize for post-stratification using an xtabs object:\cr
#'     popsize <- xtabs(~Ecoregion + Type, data = MySurveyFrame)\cr
#'
#' @param vartype Character value providing choice of the variance estimator,
#'   where \code{"Local"} = the local mean estimator, \code{"SRS"} = the simple random
#'   sampling estimator, \code{"HT"} = the Horvitz-Thompson estimator, and \code{"YG"} = the
#'   Yates-Grundy estimator.  The default value is \code{"Local"}.
#'
#' @param jointprob Character value providing choice of joint inclusion
#'   probability approximation for use with Horvitz-Thompson and Yates-Grundy
#'   variance estimators, where \code{"overton"} indicates the Overton approximation,
#'   \code{"hr"} indicates the Hartley_Rao approximation, and \code{"brewer"} equals the
#'   Brewer approximation.  The default value is \code{"overton"}.
#'
#' @param conf Numeric value providing the confidence level.  The default value
#'   is \code{95}.
#'
#' @return A data frame of population estimates for all combinations of
#'   subpopulations, categories within each subpopulation, response variables,
#'   and categories within each response variable.  Estimates are provided for
#'   proportion and total of the population plus standard error, margin of
#'   error, and confidence interval estimates.
#'
#' @section Other Functions Required:
#'   \describe{
#'     \item{\code{\link{calibrate}}}{conduct calibration for survey data}
#'     \item{\code{\link{category_est}}}{calculate category proportion and total
#'       estimates}
#'     \item{\code{\link{input_check}}}{check input values for errors,
#'       consistency, and compatibility with analytical functions}
#'     \item{\code{\link{postStratify}}}{conduct post-stratification for survey
#'       data}
#'     \item{\code{\link{survey_design}}}{creates a survey design object}
#'     \item{\code{\link{uniqueID}}}{creates unique site IDs by appending a
#'       unique number to each occurrence of a site ID}
#'     \item{\code{\link{vecprint}}}{takes an input vector and outputs a
#'       character string with line breaks inserted}
#'   }
#'
#' @author Tom Kincaid \email{Kincaid.Tom@epa.gov}
#'
#' @seealso
#'   \code{\link{calibrate}}
#'   \code{\link{category_est}}
#'   \code{\link{postStratify}}
#'   \code{\link{survey_design}}
#'
#' @keywords survey univar
#'
#' @examples
#' dframe <- data.frame(
#'   siteID = paste0("Site", 1:100),
#'   wgt = runif(100, 10, 100),
#'   xcoord = runif(100),
#'   ycoord = runif(100),
#'   stratum = rep(c("Stratum1", "Stratum2"), 50),
#'   CatVar = rep(c("north", "south", "east", "west"), 25),
#'   All_Sites = rep("All Sites", 100),
#'   Resource_Class = rep(c("Good", "Poor"), c(55, 45))
#' )
#' myvars <- c("CatVar")
#' mysubpops <- c("All_Sites", "Resource_Class")
#' mypopsize <- data.frame(
#'   Resource_Class = c("Good", "Poor"),
#'   Total = c(4000, 1500)
#' )
#' cat_analysis(dframe,
#'   vars = myvars, subpops = mysubpops, siteID = "siteID",
#'   weight = "wgt", xcoord = "xcoord", ycoord = "ycoord",
#'   stratumID = "stratum", popsize = mypopsize
#' )
#' @export
cat_analysis <- function(dframe, vars, subpops = NULL, siteID = "siteID",
                         weight = "weight", xcoord = NULL, ycoord = NULL, stratumID = NULL,
                         clusterID = NULL, weight1 = NULL, xcoord1 = NULL, ycoord1 = NULL,
                         sizeweight = FALSE, sweight = NULL, sweight1 = NULL, popcorrect = FALSE,
                         fpcsize = NULL, Ncluster = NULL, stage1size = NULL, popsize = NULL,
                         vartype = "Local", jointprob = "overton", conf = 95) {

  # Create a vector for error messages

  error_ind <- FALSE
  error_vec <- NULL

  # Create a data frame for warning messages

  warn_ind <- FALSE
  warn_df <- NULL
  fname <- "cat_analysis"

  # Ensure that the dframe argument was provided

  if (missing(dframe) | is.null(dframe)) {
    stop("\nThe dframe argument must be provided.\n")
  }

  # Ensure that the dframe argument does not contain zero rows

  if (nrow(dframe) == 0) {
    stop("\nThe dframe argument contains zero rows.\n")
  }

  # If the dframe argument is an sf object, extract coordinates from the geometry
  # column, assign values "xcoord" and "ycoord" to arguments xcoord and ycoord,
  # respectively, and drop the geometry column from the object

  if ("sf" %in% class(dframe)) {
    temp <- st_coordinates(dframe)
    xcoord <- "xcoord"
    dframe$xcoord <- temp[, "X"]
    ycoord <- "ycoord"
    dframe$ycoord <- temp[, "Y"]
    dframe <- st_set_geometry(dframe, NULL)
  }

  # Ensure that unused levels are dropped from factor variables in the dframe data
  # frame

  dframe <- droplevels(dframe)

  # Ensure that the dframe data frame contains the site ID variable

  if (!(siteID %in% names(dframe))) {
    ind <- FALSE
    error_ind <- TRUE
    msg <- paste0("The name provided for the siteID argument, \"", siteID, "\", does not occur among \nthe names for the dframe data frame.\n")
    error_vec <- c(error_vec, msg)
  } else {
    ind <- TRUE
  }

  # Check site IDs for repeat values and, as necessary, create unique site IDs and
  # output a warning message

  if (ind) {
    IDs <- dframe[, siteID]
    temp <- sapply(split(IDs, IDs), length)
    if (any(temp > 1)) {
      warn_ind <- TRUE
      temp_str <- vecprint(names(temp)[temp > 1])
      warn <- paste("The following site ID values occur more than once among the values that were \ninput to the function:\n", temp_str)
      act <- "Unique site ID values were created.\n"
      warn_df <- rbind(warn_df, data.frame(
        func = I(fname), subpoptype = NA,
        subpop = NA, indicator = NA, stratum = NA, warning = I(warn), action = I(act)
      ))
      dframe[, siteID] <- uniqueID(dframe[, siteID])
    }
  }

  # Ensure that the dframe data frame contains the survey weight variable

  if (!(weight %in% names(dframe))) {
    error_ind <- TRUE
    msg <- paste0("The name provided for the weight argument, \"", weight, "\", does not occur among \nthe names for the dframe data frame.\n")
    error_vec <- c(error_vec, msg)
  }

  # Setting a default finite population correction value for non-clustered designs
  if (popcorrect && is.null(clusterID)) {
    # if fpcsize is not provide it set it equal to the sum of the weights
    if (is.null(fpcsize)) {
      fpcsize <- sum(dframe[[weight]])
      dframe$fpcsize <- fpcsize
      fpcsize <- "fpcsize"
    } else if (is.numeric(fpcsize)) { # if it is a numeric vector create the vector
      dframe$fpcsize <- fpcsize
      fpcsize <- "fpcsize"
    }
  }

  # Create a list containing names of survey design variables

  design_names <- list(
    siteID = siteID,
    weight = weight,
    xcoord = xcoord,
    ycoord = ycoord,
    stratumID = stratumID,
    clusterID = clusterID,
    weight1 = weight1,
    xcoord1 = xcoord1,
    ycoord1 = ycoord1,
    sweight = sweight,
    sweight1 = sweight1,
    fpcsize = fpcsize,
    Ncluster = Ncluster,
    stage1size = stage1size
  )

  # Ensure that a value was provided for the vars (response variable names)
  # argument

  if (missing(vars)) {
    error_ind <- TRUE
    msg <- "A value must be provided for the vars (response variable names) argument.\n"
    error_vec <- c(error_vec, msg)
  }

  # If a value was not provided for the subpops (subpopulation names) argument,
  # assign the value "All_Sites" to the subpops argument and create a factor
  # named "All_Sites" in the dframe data frame that takes the value "All Sites"

  if (is.null(subpops)) {
    subpops <- "All_Sites"
    dframe$All_Sites <- "All Sites"
    dframe$All_Sites <- factor(dframe$All_Sites)
  }

  # Check input arguments
  temp <- input_check(dframe, design_names, vars, NULL, NULL, NULL, subpops,
    sizeweight, popcorrect, popsize, vartype, jointprob, conf,
    error_ind = error_ind, error_vec = error_vec
  )
  dframe <- temp$dframe
  vars <- temp$vars_cat
  subpops <- temp$subpops
  popsize <- temp$popsize
  vartype <- temp$vartype
  jointprob <- temp$jointprob
  error_ind <- temp$error_ind
  error_vec <- temp$error_vec

  # As necessary, output a message indicating that error messages were generated
  # during execution of the program

  if (error_ind) {
    error_vec <<- error_vec
    if (length(error_vec) == 1) {
      cat("During execution of the program, an error message was generated.  The error \nmessage is stored in a vector named 'error_vec'.  Enter the following command \nto view the error message: errorprnt()\n")
    } else {
      cat(paste("During execution of the program,", length(error_vec), "error messages were generated.  The error \nmessages are stored in a vector named 'error_vec'.  Enter the following \ncommand to view the error messages: errorprnt()\n"))
    }

    if (warn_ind) {
      warn_df <<- warn_df
      if (nrow(warn_df) == 1) {
        cat("During execution of the program, a warning message was generated.  The warning \nmessage is stored in a data frame named 'warn_df'.  Enter the following command \nto view the warning message: warnprnt()\n")
      } else {
        cat(paste("During execution of the program,", nrow(warn_df), "warning messages were generated.  The warning \nmessages are stored in a data frame named 'warn_df'.  Enter the following \ncommand to view the warning messages: warnprnt() \nTo view a subset of the warning messages (say, messages number 1, 3, and 5), \nenter the following command: warnprnt(m=c(1,3,5))\n"))
      }
    }
    stop("See the preceding message(s).")
  }

  # Assign a logical value to the indicator variable for a stratified sample

  stratum_ind <- !is.null(stratumID)

  # For a stratified sample, remove strata that contain a single site

  if (stratum_ind) {
    dframe[, stratumID] <- factor(dframe[, stratumID])
    stratum_levels <- levels(dframe[, stratumID])
    nstrata <- length(stratum_levels)
    ind <- FALSE
    for (i in 1:nstrata) {
      tst <- dframe[, stratumID] == stratum_levels[i]
      if (sum(tst) == 1) {
        warn_ind <- TRUE
        warn <- paste0("The stratum named \"", stratum_levels[i], "\" contains a single value and was removed from the analysis.\n")
        act <- "Stratum was removed from the analysis.\n"
        warn_df <- rbind(warn_df, data.frame(
          func = I(fname), subpoptype = NA,
          subpop = NA, indicator = NA, stratum = NA, warning = I(warn), action = I(act)
        ))
        dframe <- dframe[!tst, ]
        ind <- TRUE
      }
    }
    if (ind) {
      dframe[, stratumID] <- factor(dframe[, stratumID])
      stratum_levels <- levels(dframe[, stratumID])
      nstrata <- length(stratum_levels)
    }
  }

  # Assign a logical value to the indicator variable for a two-stage sample

  cluster_ind <- !is.null(clusterID)

  # Create the survey design object

  design <- survey_design(
    dframe, siteID, weight, stratum_ind, stratumID,
    cluster_ind, clusterID, weight1, sizeweight, sweight, sweight1, popcorrect,
    fpcsize, Ncluster, stage1size, vartype, jointprob
  )

  # If popsize is not equal to NULL, then call either the postStratify or
  # calibrate function, as appropriate

  if (!is.null(popsize)) {
    if (all(class(popsize) %in% c("data.frame", "table", "xtabs"))) {
      if ("data.frame" %in% class(popsize)) {
        pnames <- names(popsize)[-ncol(popsize)]
      } else {
        pnames <- names(dimnames(popsize))
      }
      design <- postStratify(design, make.formula(pnames), popsize)
    } else {
      cnames <- cal_names(make.formula(names(popsize)), design)
      pop_totals <- numeric(length(cnames))
      names(pop_totals) <- cnames
      pop_totals[1] <- sum(popsize[[1]])
      k <- 2
      for (i in names(popsize)) {
        temp <- popsize[[i]]
        for (j in 2:length(temp)) {
          pop_totals[k] <- temp[j]
          k <- k + 1
        }
      }
      design <- calibrate(design, make.formula(cnames), pop_totals)
    }
  }

  # If popsize is not equal to NULL and vartype equals "Local", then assign
  # adjusted weights to the appropriate weight variable(s) in the design$variables
  # data frame

  if (!is.null(popsize) && vartype == "Local") {
    if (cluster_ind) {
      ncluster <- length(unique(design$variables[, clusterID]))
      design$variables$wgt1 <- unique(design$variables[, Ncluster]) / ncluster
      design$variables$wgt2 <- weights(design) / design$variables$wgt1
    } else {
      design$variables$wgt <- weights(design)
    }
  }

  # Assign the confidence bound multiplier

  mult <- qnorm(0.5 + (conf / 100) / 2)

  # Create the catsum (results) data frame

  catsum <- NULL

  # Loop through all subpopulations (domains)

  for (itype in subpops) {
    lev_itype <- levels(dframe[, itype])
    nlev_itype <- length(lev_itype)

    # Loop through all response variables (vars)

    for (ivar in vars) {
      lev_ivar <- levels(dframe[, ivar])
      nlev_ivar <- length(lev_ivar)

      # Calculate estimates

      temp <- category_est(
        catsum, dframe, itype, lev_itype, nlev_itype, ivar,
        lev_ivar, nlev_ivar, design, design_names, popcorrect, vartype, conf,
        mult, warn_ind, warn_df
      )
      catsum <- temp$catsum
      warn_ind <- temp$warn_ind
      warn_df <- temp$warn_df

      # End of the loop for response variables
    }

    # End of the loop for subpopulations
  }

  # As necessary, output a message indicating that warning messages were generated
  # during execution of the program

  if (warn_ind) {
    warn_df <<- warn_df
    if (nrow(warn_df) == 1) {
      cat("During execution of the program, a warning message was generated.  The warning \nmessage is stored in a data frame named 'warn_df'.  Enter the following command \nto view the warning message: warnprnt()\n")
    } else {
      cat(paste("During execution of the program,", nrow(warn_df), "warning messages were generated.  The warning \nmessages are stored in a data frame named 'warn_df'.  Enter the following \ncommand to view the warning messages: warnprnt() \nTo view a subset of the warning messages (say, messages number 1, 3, and 5), \nenter the following command: warnprnt(m=c(1,3,5))\n"))
    }
  }

  # Assign dimension names to the catsum data frame

  dimnames(catsum) <- list(1:nrow(catsum), c(
    "Type", "Subpopulation",
    "Indicator", "Category", "nResp", "Estimate.P", "StdError.P",
    "MarginofError.P", paste0("LCB", conf, "Pct.P"),
    paste0("UCB", conf, "Pct.P"), "Estimate.U", "StdError.U",
    "MarginofError.U", paste0("LCB", conf, "Pct.U"),
    paste0("UCB", conf, "Pct.U")
  ))

  # Return the catsum data frame

  catsum
}
